config/routes.rb
Rails.application.routes.draw do
  get 'daily_jobs/index'
  resources :jobs
  resources :customers
  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  get 'welcome', to: 'sessions#welcome'

  get 'home', to: 'sessions#home' 

  get '/daily_jobs' , to: 'daily_jobs#index', :as => 'daily_jobs'

  get '/yesterday_jobs' , to: 'yesterday_jobs#index', :as => 'yesterday_jobs'

  get '/weekly_jobs' , to: 'weekly_jobs#index', :as => 'weekly_jobs'

  get '/month_jobs' , to: 'month_jobs#index', :as => 'month_jobs'

  get 'each_month', to:'month_jobs#monthly' ,:as => 'each_month'

  get 'authorized', to: 'sessions#page_requires_login'

  get '/search' => 'search#search', :as => 'search_page'

  get '/search_jobs', to: 'search#index', :as => 'search_jobs'

  get '/search_range', to: 'search#search_range', :as => 'search_range'

  get '/search_range_results', to: 'search#search_range_results', :as => 'search_range_results'



  root 'sessions#welcome'

  delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index

	end

	def search
		@join = Job.joins(:customer).includes(:user).where(user: session[:user_id]).order('jobs.created_at DESC').paginate(:page => params[:page], :per_page => 25)

		if params[:search].blank? 
			redirect_to search_jobs_path
		
		
		else 
			
			@parameter = params[:search]

			@results = @join.all.where("jobs.customer_code LIKE ? OR customers.company_name LIKE ? OR jobs.reference LIKE ?", "%#{@parameter}%","%#{@parameter}%","%#{@parameter}%")
			@resultsCount = @results.count

		end

	end

	def search_range
	
	end

	def search_range_results
		@join = Job.joins(:customer).includes(:user).where(user: session[:user_id]).order('jobs.created_at DESC').paginate(:page => params[:page], :per_page => 25)
		
		if params[:startdate].blank? && params[:enddate].blank?
			@start = Date.today
			@enddate = Date.today

		else
		@start = Date.parse(params[:startdate])
		@enddate = Date.parse(params[:enddate]) + 1.day 
		@timerange = @start..@enddate

		#@results = @join.all.where(created_at: @start..@enddate)
		@results = @join.all.where('jobs.created_at' => @timerange)

		
		end
		@totaljobs = @results.count

	end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class="container-fluid">
	<div class="bg-white content-panel">
		<h1>Search Consignments</h1>
		<hr/>

		
			<div class="row">
			<p class="extra-pad">Search by Company Name, Customer Code or by Refence</p><br>
			</div>
			<div class="row">
			<div class="col-sm">
				<%= form_tag(search_page_path, :method => "get",   
				    class: 'search-bar') do %>  

				  <div class="input-group"> 
				    <%= search_field_tag :search, params[:search], placeholder: "Search Jobs", minlength: 3, class: "form-control" %> 

					    <div class="input-group-btn">  
					      <%= button_tag " ",:id => 'searchBtn',:class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
					    </div> 
				    <% end %> 
				  </div> 
			</div>
			</div>

			
		
		<br>
		<br>
	</div>
</div>

app/views/search/search.html.erb
<div class="container-fluid">
  <div class="bg-white content-panel">
    <h1>Search Consignments</h1>
    <hr/>

    
      <div class="row">
      <p class="extra-pad">Search by Company Name, Customer Code or by Refence</p><br>
      </div>
      <div class="row">
      <div class="col-sm">
        <%= form_tag(search_page_path, :method => "get",   
            class: 'search-bar') do %>  

          <div class="input-group"> 
            <%= search_field_tag :search, params[:search], placeholder: "Search Jobs", minlength: 3, class: "form-control" %> 

              <div class="input-group-btn">  
                <%= button_tag " ",:id => 'searchBtn',:class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
              </div> 
            <% end %> 
          </div> 
      </div>
      </div>

      
    
    <br>
    <br>

    


    <% if @resultsCount >= 1 %>
    <p>Showing <strong><%= @resultsCount %></strong> Results for : <strong><%= params[:search] %></strong></p>
    <br>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Job Number</th>
          <th>Company Name</th>
          <th>Reference</th>
          <th>Parcels</th>
          <th>Pallets</th>
          <th>Bundles</th>
          <th>Address 1</th>
          <th>Address 2</th>
          <th>Adrdres 3</th>
          <th>Date Added</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @results.each do |job| %>
          <tr>
            <td><%= job.id %></td>
            <td><%= link_to job.customer.company_name, job.customer %></td>
            <td class="center-table"><%= job.reference %></td>
            <td class="center-table"><%= job.parcels %></td>
            <td class="center-table"><%= job.pallets %></td>
            <td class="center-table"><%= job.bundles %></td>
            <td><%= job.customer.address1 %></td>
            <td><%= job.customer.address2 %></td>
            <td><%= job.customer.address3 %></td>
            <td><%= job.created_at.to_date.strftime('%d-%m-%y') %></td>
            <td><%= link_to 'Show', job %></td>
            <td><%= link_to 'Edit', edit_job_path(job) %></td>
            <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row">
        <div id="pagination">
        <%= will_paginate @results %>
        </div>
        </div>
    <% else %>
      <hr/>
      <p>No Results Found</p>
    <% end %>


  </div>
</div>

app/views/search/search_range.html.erb
<div class="container-fluid">
  <div class="bg-white content-panel">
    <h1>Search date range</h1>
    <hr/>

    <p>Select a start date and end date to seach</p>
    <br>

    <%= form_tag(search_range_results_path, :method => "get",   
          class: 'seach-range') do %> 
          <div id="searchRangeBar" class="row">
            <div class="col-6 row">
              <div class="col-3">
                <p>Start Date: </p>
              </div>
              <div class="col-7">
              <%= date_field_tag :startdate, params[:startdate],  class: "form-control" %> 
              </div>
            </div>
            <div class="col-6 row">
              <div class="col-3">
                <p>End Date:</p>
              </div>
              <div class="col-7">
                <%= date_field_tag :enddate, params[:enddate],  class: "form-control" %>
              </div> 
              <div class="col-2">
                <%= button_tag "Select", :class => 'btn btn-info',:name => nil%> 
              </div>
            </div>
          </div>
          <br>
          <br>
    <% end %> 

  </div>
</div>

app/views/search/search_range_results.html.erb
<div class="container-fluid">
  <div class="bg-white content-panel">
    <h1>Search date range</h1>
    <hr/>

    <p>Select a start date and end date to seach</p>
    <br>

    <%= form_tag(search_range_results_path, :method => "get",   
          class: 'seach-range') do %> 
          <div id="searchRangeBar" class="row">
            <div class="col-6 row">
              <div class="col-3">
                <p>Start Date: </p>
              </div>
              <div class="col-7">
              <%= date_field_tag :startdate, params[:startdate],  class: "form-control" %> 
              </div>
            </div>
            <div class="col-6 row">
              <div class="col-3">
                <p>End Date:</p>
              </div>
              <div class="col-7">
                <%= date_field_tag :enddate, params[:enddate],  class: "form-control" %>
              </div> 
              <div class="col-2">
                <%= button_tag "Select", :class => 'btn btn-info',:name => nil%> 
              </div>
            </div>
          </div>
     
    <% end %> 
    <br>
    <br>
    <% if @results.count >= 1 %>
      <p>Showing <strong><%= @results.count%></strong>  results between : <strong><%=@start.strftime('%d-%m-%Y') %></strong> and <strong><%= @enddate.strftime('%d-%m-%Y') %></strong></p>
      <br>
        <table class="table table-striped">
          <thead>
        <tr>
          <th>Job Number</th>
          <th>Company Name</th>
          <th>Reference</th>
          <th>Parcels</th>
          <th>Pallets</th>
          <th>Bundles</th>
          <th>Address 1</th>
          <th>Address 2</th>
          <th>Adrdres 3</th>
          <th>Date Added</th>
          <th colspan="3"></th>
        </tr>
      </thead>

          <tbody>
            <% @results.each do |job| %>
              <tr>
                <td><%= job.id %></td>
                <td><%= link_to job.customer.company_name, job.customer %></td>
                <td class="center-table"><%= job.reference %></td>
                <td class="center-table"><%= job.parcels %></td>
                <td class="center-table"><%= job.pallets %></td>
                <td class="center-table"><%= job.bundles %></td>
                <td><%= job.customer.address1 %></td>
                <td><%= job.customer.address2 %></td>
                <td><%= job.customer.address3 %></td>
                <td><%= job.created_at.to_date.strftime('%d-%m-%y') %></td>
                <td><%= link_to 'Show', job %></td>
                <td><%= link_to 'Edit', edit_job_path(job) %></td>
                <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row">
        <div id="pagination">
        <%= will_paginate @results %>
        </div>
        </div>
        <br>
      <% else %>
      <hr/>
      <p>No Results Found</p>
      <% end %>
  </div>
</div>