config/routes.rb
Rails.application.routes.draw do
  get 'daily_jobs/index'
  resources :jobs
  resources :customers
  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  get 'welcome', to: 'sessions#welcome'

  get 'home', to: 'sessions#home' 

  get '/daily_jobs' , to: 'daily_jobs#index', :as => 'daily_jobs'

  get '/yesterday_jobs' , to: 'yesterday_jobs#index', :as => 'yesterday_jobs'

  get '/weekly_jobs' , to: 'weekly_jobs#index', :as => 'weekly_jobs'

  get '/month_jobs' , to: 'month_jobs#index', :as => 'month_jobs'

  get 'each_month', to:'month_jobs#monthly' ,:as => 'each_month'

  get 'authorized', to: 'sessions#page_requires_login'

  get '/search' => 'search#search', :as => 'search_page'

  get '/search_jobs', to: 'search#index', :as => 'search_jobs'

  get '/search_range', to: 'search#search_range', :as => 'search_range'

  get '/search_range_results', to: 'search#search_range_results', :as => 'search_range_results'



  root 'sessions#welcome'

  delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/month_jobs_controller.rb
class MonthJobsController < ApplicationController
	def index
	@today = Date.today
	

	
	@monthstart = @today.beginning_of_month
	@lastmonth = @monthstart - 1.month
	@monthrange = @monthstart..@today + 1


	@jobs = Job.joins(:customer).includes(:user).where(user: session[:user_id])

	@monthJobs = @jobs.all.where("jobs.created_at" => @monthrange)
	@monthCount = @monthJobs.count
	@monthparcels = @monthJobs.sum(:parcels)
	@monthpallets = @monthJobs.sum(:pallets)
	@monthbundles = @monthJobs.sum(:bundles)
	@monthByDay = @monthJobs.group("DATE(jobs.created_at)").count
	@monthEachDay = @monthJobs.group("DATE(jobs.created_at)").pluck(:created_at ,'count(jobs.created_at)','sum(jobs.parcels)', 'sum(jobs.pallets)','sum(jobs.bundles)')
	@results = @monthJobs.paginate(:page => params[:page], :per_page => 25)

	end

	def monthly
		

		@monthParam = params[:jobMonth]
		

		
		@jobs = Job.joins(:customer).includes(:user).where(user: session[:user_id])
		@months = Date::MONTHNAMES
		@monthNum = @monthParam.strip.last(2).to_f
		@year = @monthParam.strip.first(4)
		@monthName = @months[@monthNum]

		@jobsThisMonth = @jobs.all.where('jobs.created_at LIKE ?',"%#{@monthParam}%")
		@monthCount = @jobsThisMonth.count
		@monthparcels = @jobsThisMonth.sum(:parcels)
		@monthpallets = @jobsThisMonth.sum(:pallets)
		@monthbundles = @jobsThisMonth.sum(:bundles)
		@monthByDay = @jobsThisMonth.group("DATE(jobs.created_at)").count
		@monthEachDay = @jobsThisMonth.group("DATE(jobs.created_at)").pluck(:created_at , 'count(jobs.created_at)', 'sum(jobs.parcels)', 'sum(jobs.pallets)','sum(jobs.bundles)')
		@results = @jobsThisMonth.paginate(:page => params[:page], :per_page => 25)
	end
end

app/helpers/month_jobs_helper.rb
module MonthJobsHelper
end

app/views/month_jobs/index.html.erb
<div class="fluid-container">
  <div class="bg-white content-panel">
    <h1>Consignments added this Month</h1>
    <hr/>



    <div id="month-search" class="row">
      <%= form_tag(each_month_path, :method => "get",   
        class: 'center row month-search') do %> 

  
        <div class="center">
          <label for="bdaymonth">Select Month/Year:</label>
          <input type="month" id="jobMonth" name="jobMonth">
           <%= button_tag "Select", :id => 'monthSelect', :class => 'btn btn-info',:name => nil%>  
        </div>
      <% end %>
    </div>
    <br><br>

    <% if @monthJobs.count > 0 %>
    <div class="row">
    <%= render partial: "sessions/month-panel" %>
  </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Job Number</th>
          <th>Company Name</th>
          <th>Reference</th>
          <th>Parcels</th>
          <th>Pallets</th>
          <th>Bundles</th>
          <th>Address 1</th>
          <th>Address 2</th>
          <th>Address 3</th>
          <th>Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @results.each do |job| %>
          <tr>
            <td><%= job.id %></td>
            <td><%= link_to job.customer.company_name, job.customer%></td>
            <td class='center-table'><%= job.reference %></td>
            <td class='center-table'><%= job.parcels %></td>
            <td class='center-table'><%= job.pallets %></td>
            <td class='center-table'><%= job.bundles %></td>
            <td><%= job.customer.address1 %></td>
            <td><%= job.customer.address2 %></td>
            <td><%= job.customer.address3 %></td>
            <td><%= job.created_at.to_date.strftime('%d-%m-%y') %></td>
            <td><%= link_to 'Show', job %></td>
            <td><%= link_to 'Edit', edit_job_path(job) %></td>
            <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row">
          <div id="pagination">
            <%= will_paginate @results %>
          </div>
        </div>
    <% else %>
    	<p>No Consignments added this Month</p>
    <% end %>

    <br>
      </div>
</div>
<script>
document.getElementById("jobMonth").required = true;
  </script>

app/views/month_jobs/monthly.html.erb
<div class="container-fluid">
  <div class="bg-white content-panel">
  	<h1>Consignments added in <%= @monthName%> <%= @year%></h1>
    <hr/>
    <div id="month-search" class="row">
      <%= form_tag(each_month_path, :method => "get",   
        class: 'center row month-search') do %> 

  
        <div class="center">
          <label for="bdaymonth">Select Month/Year:</label>
          <input type="month" id="jobMonth" name="jobMonth">
           <%= button_tag "Select", :id => 'monthSelect', :class => 'btn btn-info',:name => nil%>  
        </div>
      <% end %>
    </div>
    <br><br>

  	<% if @jobsThisMonth.count > 0 %>
    <div class="row">
    <%= render partial: "sessions/month-panel" %>
  </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Job Number</th>
          <th>Company Name</th>
          <th>Reference</th>
          <th>Parcels</th>
          <th>Pallets</th>
          <th>Bundles</th>
          <th>Adrress 1</th>
          <th>Adrress 2</th>
          <th>Adrress 3</th>
          <th>Date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @results.each do |job| %>
          <tr>
            <td><%= job.id %></td>
            <td><%= link_to job.customer.company_name , job.customer%></td>
            <td class="center-table"><%= job.reference %></td>
            <td class="center-table"><%= job.parcels %></td>
            <td class="center-table"><%= job.pallets %></td>
            <td class="center-table"><%= job.bundles %></td>
            <td><%= job.customer.address1 %></td>
            <td><%= job.customer.address2 %></td>
            <td><%= job.customer.address3 %></td>
            <td><%= job.created_at.to_date.strftime('%d-%m-%y') %></td>
            <td><%= link_to 'Show', job %></td>
            <td><%= link_to 'Edit', edit_job_path(job) %></td>
            <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row">
          <div id="pagination">
            <%= will_paginate @results %>
          </div>
        </div>
    <% else %>
    	<p>No Consignments added this Month</p>
    <% end %>

    <br>
      </div>

  </div>
</div>
<script>
document.getElementById("jobMonth").required = true;
  </script>