config/routes.rb
Rails.application.routes.draw do
  get 'daily_jobs/index'
  resources :jobs
  resources :customers
  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  get 'welcome', to: 'sessions#welcome'

  get 'home', to: 'sessions#home' 

  get '/daily_jobs' , to: 'daily_jobs#index', :as => 'daily_jobs'

  get '/yesterday_jobs' , to: 'yesterday_jobs#index', :as => 'yesterday_jobs'

  get '/weekly_jobs' , to: 'weekly_jobs#index', :as => 'weekly_jobs'

  get '/month_jobs' , to: 'month_jobs#index', :as => 'month_jobs'

  get 'each_month', to:'month_jobs#monthly' ,:as => 'each_month'

  get 'authorized', to: 'sessions#page_requires_login'

  get '/search' => 'search#search', :as => 'search_page'

  get '/search_jobs', to: 'search#index', :as => 'search_jobs'

  get '/search_range', to: 'search#search_range', :as => 'search_range'

  get '/search_range_results', to: 'search#search_range_results', :as => 'search_range_results'



  root 'sessions#welcome'

  delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
	belongs_to :user
	has_many :jobs
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @test = Customer.where(user_id: session[:user_id]).paginate(:page => params[:page], :per_page => 25)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @alljobs = Job.joins(:customer).includes(:user).where(user: session[:user_id]).order('jobs.created_at DESC')
    @customerjobs = @alljobs.all.where("customers.customer_code LIKE ?", @customer.customer_code)
    @results = @customerjobs.paginate(:page => params[:page], :per_page => 25)
    @totalJobs = @customerjobs.count
    @groupJobs = Job.joins(:customer).includes(:user).where(user: session[:user_id]).where("customers.customer_code LIKE ?", @customer.customer_code)
    @monthGroup = @groupJobs.group("strftime('%m',jobs.created_at)").count
    @monthNames = Date::MONTHNAMES
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:customer_code, :company_name, :address1, :address2, :address3, :eircode, :user_id)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="format-form">
  <div class="field">
    <%= form.label :customer_code %>
    <%= form.text_field :customer_code %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2 %>
  </div>

  <div class="field">
    <%= form.label :address3 %>
    <%= form.text_field :address3 %>
  </div>

  <div class="field">
    <%= form.label :eircode %>
    <%= form.text_field :eircode %>
  </div>

  <div class="field hide">
    <%= form.label :user_id %>
    <input type="text" id="user_id" name="customer[user_id]" value="<%= current_user.id %>">
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <br/>
</div>
<% end %>

app/views/customers/edit.html.erb
<div class="container-fluid">
	<div class="bg-white content-panel">

		<h1>Editing Customer</h1>
		<hr/>
		<%= render 'form', customer: @customer %>

		<%= link_to 'Show', @customer %> |
		<%= link_to 'Back', customers_path %>
	</div>
</div>

app/views/customers/index.html.erb
<div class="container-fluid">
  <div class="bg-white content-panel">
    <p id="notice"><%= notice %></p>

    <h1>Customers</h1>
    <hr/>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Customer code</th>
          <th>Company name</th>
          <th>Address 1</th>
          <th>Address 2</th>
          <th>Address 3</th>
          <th>Eircode</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @test.each do |customer| %>
          <tr>
            <td><%= customer.customer_code %></td>
            <td><%= link_to customer.company_name, customer %></td>
            <td><%= customer.address1 %></td>
            <td><%= customer.address2 %></td>
            <td><%= customer.address3 %></td>
            <td><%= customer.eircode %></td>
            <td><%= link_to 'Show', customer %></td>
            <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
            <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row">
          <div id="pagination">
            <%= will_paginate @test %>
          </div>
        </div>

    <br>

    <button type="button" class="btn btn-primary"><%= link_to 'New Customer', new_customer_path %></button>
  </div>
</div>

app/views/customers/new.html.erb
<div class="container-fluid">
	<div class="bg-white content-panel">
		<h1>New Customer</h1>
		<hr/>
		<%= render 'form', customer: @customer %>

		<%= link_to 'Back', customers_path %>
	</div>
</div>

app/views/customers/show.html.erb
<div class="container-fluid">
  <div class="bg-white content-panel">
    <div class="row">
      <div class="row-100">
          <h1><%= @customer.company_name %></h1>
          <hr/>
        </div>
      <div class="col-sm">
        <p id="notice"><%= notice %></p>


        <p>
          <strong>Customer code:</strong>
          <%= @customer.customer_code %>
        </p>

        <p>
          <strong>Company name:</strong>
          <%= @customer.company_name %>
        </p>

        <p>
          <strong>Address1:</strong>
          <%= @customer.address1 %>
        </p>

        <p>
          <strong>Address2:</strong>
          <%= @customer.address2 %>
        </p>

        <p>
          <strong>Address3:</strong>
          <%= @customer.address3 %>
        </p>

        <p>
          <strong>Eircode:</strong>
          <%= @customer.eircode %>
        </p>
      </div>

      <div class="col-sm">
        <canvas id="chart1">
        </canvas>
      </div>
    </div>

    <%= link_to 'Edit', edit_customer_path(@customer) %> |
    <%= link_to 'Back', customers_path %>


    <% if @totalJobs >= 1 %>
    <h3>Total Consignments: <%= @totalJobs %></h3>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Job Number</th>
          <th>Company Name</th>
          <th>Reference</th>
          <th>Parcels</th>
          <th>Pallets</th>
          <th>Bundles</th>
          <th>Address 1</th>
          <th>Address 2</th>
          <th>Adrdres 3</th>
          <th>Date Added</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @results.each do |job| %>
          <tr>
            <td><%= job.id %></td>
            <td><%= job.customer.company_name %></td>
            <td class="center-table"><%= job.reference %></td>
            <td class="center-table"><%= job.parcels %></td>
            <td class="center-table"><%= job.pallets %></td>
            <td class="center-table"><%= job.bundles %></td>
            <td><%= job.customer.address1 %></td>
            <td><%= job.customer.address2 %></td>
            <td><%= job.customer.address3 %></td>
            <td><%= job.created_at %></td>
            <td><%= link_to 'Show', job %></td>
            <td><%= link_to 'Edit', edit_job_path(job) %></td>
            <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row">
          <div id="pagination">
            <%= will_paginate @results %>
          </div>
        </div>
    <% end %>
  </div>

</div>

<script>
var monthChart = document.getElementById('chart1').getContext('2d');
var chart = new Chart(monthChart, {
    // The type of chart we want to create
    type: 'bar',

    // The data for our dataset
    data: {
        labels: [
          <% @monthGroup.each do |a|%>
              '<%= @monthNames[a[0].to_f] %>',
            <% end %>
        ],
        datasets: [{
            label: 'Consignments',
            backgroundColor: ['rgb(236, 219, 83)',
                              'rgb(227,65,50)',
                              'rgb(108,160,220)',
                              'rgb(147,71,66)',
                              'rgb(219,178,209)',
                              'rgb(235,150,135)',
                              'rgb(0,166,140)',
                              'rgb(100,83,148)',
                              'rgb(108,79,60)',
                              'rgb(235,225,223)',
                              'rgb(188,108,167)',
                              'rgb(191,216,51)'],
            borderColor: 'rgb(255, 99, 132)',
            data: [
            <% @monthGroup.each do |a|%>
              <%= a[1] %>,
            <% end %>
            ],
            
        }]

    },

    // Configuration options go here
    options: {
      scales:{
        yAxes:[{
          display:true,
          ticks:{
            suggestedMin:0,
            beginAtZero:true
          }
        }]
      }
    }
});
  </script>





  