config/routes.rb
Rails.application.routes.draw do
  get 'daily_jobs/index'
  resources :jobs
  resources :customers
  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  get 'welcome', to: 'sessions#welcome'

  get 'home', to: 'sessions#home' 

  get '/daily_jobs' , to: 'daily_jobs#index', :as => 'daily_jobs'

  get '/yesterday_jobs' , to: 'yesterday_jobs#index', :as => 'yesterday_jobs'

  get '/weekly_jobs' , to: 'weekly_jobs#index', :as => 'weekly_jobs'

  get '/month_jobs' , to: 'month_jobs#index', :as => 'month_jobs'

  get 'each_month', to:'month_jobs#monthly' ,:as => 'each_month'

  get 'authorized', to: 'sessions#page_requires_login'

  get '/search' => 'search#search', :as => 'search_page'

  get '/search_jobs', to: 'search#index', :as => 'search_jobs'

  get '/search_range', to: 'search#search_range', :as => 'search_range'

  get '/search_range_results', to: 'search#search_range_results', :as => 'search_range_results'



  root 'sessions#welcome'

  delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<div class="vertical-nav " id="sidebar">
  
 

 

      <ul class="nav flex-column  mb-0">
        <li class="nav-item">
          <%= link_to 'Home', home_path %>
        </li>

        <li class="nav-item">
           <a data-toggle="collapse" href="#collapse1">Jobs</a>
            <ul id="collapse1" class="collapse">
              <li class="nav-item">
                <%= link_to 'Jobs List', jobs_path %>
              </li>
              <li>
                <%= link_to 'Create Job', new_job_path %>
              </li>
              <li>
                <%= link_to 'Jobs Added Today', daily_jobs_path %>
              </li>
              <li>
                <%= link_to 'Search Jobs', search_jobs_path %>
              </li>
              <li>
                <%= link_to 'Search Range', search_range_path %>
              </li>
            </ul>
        </li>
          
        <li class="nav-item">
          <a data-toggle="collapse" href="#collapse2">Customers</a>
            <ul id="collapse2" class="collapse">
              <li>
               <%= link_to 'Customer List', customers_path%>
              </li>
              <li>
               <%= link_to 'Add Customers', new_customer_path%>
              </li>
            </ul>
        </li>
        
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: "delete" %>
        </li>
       
      </ul>  
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project11</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <style>
#chartdiv {
  width: 100%;
  height: 750px;
}

</style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'mystyles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://www.amcharts.com/lib/4/core.js"></script>
<!--<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/kelly.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>-->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>

<div class="my-container">

<% if logged_in? %>


    <div class="vertical-nav " id="sidebar">
  
 

 

      <ul class="nav flex-column  mb-0">
        <li class="nav-item">
          <%= link_to 'Dashboard', home_path %>
        </li>

        <li class="nav-item">
           <a data-toggle="collapse" href="#collapse1">Consignments</a>
            <ul id="collapse1" class="collapse">
              <li class="nav-item">
                <%= link_to 'All Consignments', jobs_path %>
              </li>
              <li>
                <%= link_to 'New Consignment', new_job_path %>
              </li>
              <li>
                <%= link_to 'Consignments Added Today', daily_jobs_path %>
              </li>
              <li>
                <%= link_to 'Search Consignments', search_jobs_path %>
              </li>
              <li>
                <%= link_to 'Search Range', search_range_path %>
              </li>
            </ul>
        </li>
          
        <li class="nav-item">
          <a data-toggle="collapse" href="#collapse2">Customers</a>
            <ul id="collapse2" class="collapse">
              <li>
               <%= link_to 'Customer List', customers_path%>
              </li>
              <li>
               <%= link_to 'Add Customers', new_customer_path%>
              </li>
            </ul>
        </li>
        
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: "delete" %>
        </li>
       
      </ul>  
  </div>
<% end %>



    
   <div class="page-content p-5" id="content">
  <!-- Toggle button -->
  

  <!-- Demo content -->
  <%= yield %>
  </div>
</div>
  </body>
</html>